### ISSUE TITLE
After new Chrome update app breaks with "handler exists"

### ISSUE THREAD

**Issue by xanatas** [iron-meteor/iron-middleware-stack#9]
Exception in callback of async function: Error: Handler with name 'hookWithOptions' already exists.
Only in Chrome 64bit OSX & Linux
Version 51.0.2704.63 (64-bit)
Any fix suggested?

**Comment by wallslide** [comment]
It has already been fixed. You just need to `meteor update iron:middleware-stack`

You can see the issue here:

https://github.com/iron-meteor/iron-router/issues/1513#issuecomment-200636661

**Comment by vardhans** [comment]
It works after the update. Thank a lot.
